import React from "react";
import Footer from "../components/footer";

export default function Services() {
  return (
    <div className="text-blue-300">
      <h1 className="text-red-500 font-serif text-center text-3xl">Services</h1>
     <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eveniet provident perferendis quisquam consequatur nisi nam reiciendis officiis maiores sequi doloribus, ullam voluptas similique laboriosam exercitationem, cupiditate est aliquid culpa a quam quia soluta architecto. Fugit, voluptates. Unde officiis repudiandae aperiam dolorem qui possimus maiores labore quod? Eius voluptate nemo, impedit itaque magni quae omnis inventore neque quibusdam dolor tempora numquam perspiciatis ullam aperiam laboriosam harum dignissimos fuga aliquid similique quisquam doloribus veritatis beatae dolorem! Nesciunt nam minima eos laboriosam! Nobis, consequuntur. Eveniet tempore, porro molestiae, tempora molestias incidunt nihil ab possimus doloremque blanditiis, impedit dolores odio voluptas quas praesentium debitis minus excepturi ratione non libero. Ipsa a fuga adipisci. Alias sunt dicta vel nemo ea asperiores, aliquam quas! Iusto, repellendus minima nihil ad voluptas voluptatibus qui illum enim amet aut deleniti error est quod porro cupiditate quam, doloremque modi dignissimos eos itaque eligendi. Officia, perferendis dicta itaque accusamus veniam repellendus. Esse iure tenetur quo velit harum vel voluptatem vero, ad ducimus debitis neque voluptas dicta aspernatur nihil voluptates nesciunt et fugiat sed iusto itaque deserunt nulla animi quam? Est quos sequi ad. Ea at, amet cupiditate ab quis doloribus porro veniam quaerat maxime optio magnam animi rem, magni necessitatibus? Cum numquam dicta voluptatibus libero. Reiciendis rem ipsam voluptate sequi distinctio culpa ullam numquam, dolorem expedita quaerat ducimus, magni excepturi magnam voluptas possimus facere, nobis deleniti molestias cupiditate sapiente eius vero non amet molestiae? Debitis eum itaque, hic in laboriosam dolorem, rem porro est et distinctio, maiores tenetur. Nulla, fugiat officiis atque, aliquam ullam id quo nemo ducimus corrupti quas aliquid voluptate. Autem dolor nemo voluptatem magni quibusdam quod vitae modi pariatur consequuntur! Animi fugiat provident impedit, assumenda ex eveniet aperiam veritatis totam nostrum dolores sunt libero numquam unde voluptatibus, repudiandae dolore. Sint odit iusto et accusantium voluptatem ea, corporis fugit iure molestiae, voluptatum, error nobis exercitationem ad vitae. Obcaecati praesentium asperiores vel necessitatibus aliquid reiciendis, minus quasi tempore assumenda quia suscipit mollitia consequuntur omnis eum, facilis exercitationem molestias, ad rem sapiente numquam blanditiis sequi. Vero aliquam voluptatibus exercitationem omnis, at facilis ex, debitis ducimus dolorem delectus eligendi, repudiandae adipisci nemo?</p>
    </div>
  );
}
